# Generated by Django 3.2.8 on 2021-11-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Entre o nome', max_length=100)),
                ('email', models.EmailField(help_text='Informe o email', max_length=254)),
                ('telefone', models.CharField(help_text='Telefone com DDD e DDI', max_length=20)),
                ('dtNasc', models.DateField(help_text='Nascimento no formato DD/MM/AAAA', verbose_name='Data de nascimento')),
            ],
        ),
    ]
